//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public book()
        {
            this.bookClients = new HashSet<bookClient>();
        }
    
        public int id { get; set; }
        public string bookName { get; set; }
        public string tittle { get; set; }
        public string edition { get; set; }
        public Nullable<int> quality { get; set; }
    
        public virtual ICollection<bookClient> bookClients { get; set; }
    }
}
